name: shellcheck
on: { workflow_call: {} }
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          if compgen -G "**/*.sh" > /dev/null; then
            sudo apt-get update && sudo apt-get install -y shellcheck
            shellcheck **/*.sh
          else
            echo "No shell scripts found."
          fi
